apiVersion: v1
kind: ConfigMap
metadata:
  name: howdy-client-config
data:
  app.yaml: |
    hello:
      host: 'xds:///howdy-server-listener'
  xds_bootstrap.json: |
    {
      "xds_servers": [
        {
          "server_uri": "xds-server.default.svc.cluster.local:18000"
        }
      ],
      "node": {
        "id": "25386353-c3e2-42f5-ad65-2b003c3386f5",
        "metadata": {
          "TEST_PROJECT_ID": "We45523"
        },
        "locality": {
          "zone": "my-zone"
        }
      }
    }